name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # لاحظ كتابة الاسم بدقة هنا: ArtemSerebrennkov (بـ 2 'n' في الوسط و 2 'n' في الآخر)
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.9

      - name: Upload APK
        # استخدمنا v4 لحل مشكلة الـ Deprecation التي ظهرت في صورتك
        uses: actions/upload-artifact@v4
        with:
          name: my-app-package
          path: bin/*.apk
